### ISSUE TITLE
ImportError: cannot import name RobustScaler

### ISSUE THREAD

**Issue by Jeeva-G** [rhiever/tpot#143]
[provide general introduction to the issue and why it is relevant to this repository]

## Trying to create the TPOT instance

I am just trying to create the TPOT instance, I have installed all the required packages. But i am getting this "cannot import name RobustScaler" error.

## Process to reproduce the issue

from tpot import TPOT
pipeline_optimizer = TPOT(generations=100, random_state=42, verbosity =2)

## `Import error` screenshot

<img width="990" alt="screenshot 2016-05-11 12 52 17" src="https://cloud.githubusercontent.com/assets/6980874/15166892/79d6e95e-1777-11e6-93f2-8ab44fe97dcf.png">

## Installed packages

<img width="813" alt="screenshot 2016-05-11 12 55 01" src="https://cloud.githubusercontent.com/assets/6980874/15166909/adfd877e-1777-11e6-9a5c-bfce3a097282.png">

**Comment by teaearlgraycold** [comment]
What version of scikit-learn do you have installed?

**Comment by Jeeva-G** [comment]
I had scikit-learn-0.16.1, I uninstalled and reinstalled scikit-learn-0.17.1 now, still the issue persists.

**Comment by teaearlgraycold** [comment]
That class was new in 0.17 so I'm not surprised it didn't work with 0.16. Are you sure that 0.17 is being used by TPOT? If you're using Anaconda it's possible that you modified your system installation of Python and not your local installation.

This should output your current version:

`$ python`

```python
import sklearn
sklearn.__version__ # '0.17.1'
```

**Comment by Jeeva-G** [comment]
Yes. you are genius. Running that script in my IPython notebook gives me 0.16.1 . How does that work? How do I change my IPython to use this version?

**Comment by teaearlgraycold** [comment]
They include a version string in the scikit-learn module:

https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/__init__.py#L40

You're just outputting the string to the console by typing `sklearn.__version__`.

---

When you run `$ sudo pip install <package>` you're installing packages to your system, not to your local installation.

Make sure you followed the installation instructions exactly (http://rhiever.github.io/tpot/installing/).

If it says to use `pip` instead of `sudo pip`, *then only type `pip`*.

**Comment by Jeeva-G** [comment]
All good. I did manage to use the right version by uninstalling and reinstalling scikit-learn. Sudo was not an issue here. It works now. Thanks for pointing me to the right version.
